service: gopher-holes-unlimited

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}
  logs:
    restApi: true
  lambdaHashingVersion: 20201221
  environment:
    REGION: ${self:provider.region}
    SOURCE_QUEUE_URL: 
      Fn::ImportValue: ${self:custom.sqs.gopherHolesSqsStack}:${self:provider.stage}:SourceQueueURL
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - sqs:SendMessage
          Resource: 
            - Fn::ImportValue: ${self:custom.sqs.gopherHolesSqsStack}:${self:provider.stage}:SourceQueueARN

package:
  patterns:
    - '!resources/**'
    - '!mocks/**'

custom:
  sqs:
    gopherHolesSqsStack: gopher-holes-unlimited-sqs

functions:
  gopher-create-quque:
    handler: src/handlers/create.queue
    events:
      - http:
          path: /gopher/create
          method: POST
  
  gopher-create-process:
    handler: src/handlers/create.process
    events:
      - sqs:
          arn: 
            Fn::ImportValue: ${self:custom.sqs.gopherHolesSqsStack}:${self:provider.stage}:SourceQueueARN
          batchSize: 1

plugins:
  - serverless-webpack
