service: gopher-holes-unlimited

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}
  logs:
    restApi: true
  lambdaHashingVersion: 20201221
  environment:
    REGION: ${self:provider.region}
    TABLE_NAME: ${self:custom.dynamodb.tableName}
    SOURCE_QUEUE_URL: 
      Fn::ImportValue: ${self:custom.sqs.gopherHolesSqsStack}:${self:provider.stage}:SourceQueueURL

package:
  patterns:
    - '!resources/**'

custom:
  sqs:
    gopherHolesSqsStack: gopher-holes-unlimited-sqs
  dynamodb:
    tableName: gopher-holes-unlimited-${self:provider.stage}

functions:
  gopher-create-queue:
    handler: src/handlers/create.queue
    role: LambdaRole
    events:
      - http:
          path: /gopher/create
          method: POST
  
  gopher-create-process:
    handler: src/handlers/create.process
    role: LambdaRole
    events:
      - sqs:
          arn: 
            Fn::ImportValue: ${self:custom.sqs.gopherHolesSqsStack}:${self:provider.stage}:SourceQueueARN
          batchSize: 1

resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-${self:provider.region}-lambda-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-${self:provider.region}-dynamodb-role
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource: 
                    - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.dynamodb.tableName}
                    - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.dynamodb.tableName}/index/*
          - PolicyName: ${self:service}-${self:provider.stage}-${self:provider.region}-sqs-role
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: 
                    - sqs:SendMessage
                  Resource: 
                    - Fn::ImportValue: ${self:custom.sqs.gopherHolesSqsStack}:${self:provider.stage}:SourceQueueARN

plugins:
  - serverless-webpack
