service: gopher-holes-unlimited-sqs

provider:
  name: aws
  profile: nadtakan
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-1"}

resources:
  Resources:
    GopherHolesSQS:
      Type: AWS::SQS::Queue
      Properties: 
        RedrivePolicy: 
          deadLetterTargetArn: 
            Fn::GetAtt: 
              - "GopherHolesDLQ"
              - "Arn"
          maxReceiveCount: 5
        QueueName: gopherHolesQueue

    GopherHolesDLQ: 
      Type: AWS::SQS::Queue
  
  Outputs:
    SourceQueueURL: 
      Description: "URL of source queue"
      Value: 
        Ref: "GopherHolesSQS"
      Export:
        Name: ${self:service}:${self:provider.stage}:SourceQueueURL

    SourceQueueARN: 
      Description: "ARN of source queue"
      Value: 
        Fn::GetAtt: 
          - "GopherHolesSQS"
          - "Arn"
      Export:
        Name: ${self:service}:${self:provider.stage}:SourceQueueARN

    DeadLetterQueueURL: 
      Description: "URL of dead-letter queue"
      Value: 
        Ref: "GopherHolesDLQ"
      Export:
        Name: ${self:service}:${self:provider.stage}:DeadLetterQueueURL

    DeadLetterQueueARN: 
      Description: "ARN of dead-letter queue"
      Value: 
        Fn::GetAtt: 
          - "GopherHolesDLQ"
          - "Arn"
      Export:
        Name: ${self:service}:${self:provider.stage}:DeadLetterQueueARN